In [36]:
import numpy as np
import pandas as pd
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

In [37]:
F1 = '/Users/herpov/Documents/mnt/tuba_home/tcr-pmhc-sc-project/experiments/exp13/run1/lib/experimental/15mer_oligos.xlsx'
F2 = '/Users/herpov/Documents/mnt/tuba_home/tcr-pmhc-sc-project/experiments/exp13/run1/lib/experimental/Overview.xlsx'
FA = '/Users/herpov/Documents/PhD/Academic/Projects/misc_netTCR/loose data/bc25mer.240k.fasta'

In [55]:
OA = '/Users/herpov/Documents/mnt/tuba_home/tcr-pmhc-sc-project/tools/barcode_oligos/oligo_a.25mer.fa'
OB = '/Users/herpov/Documents/mnt/tuba_home/tcr-pmhc-sc-project/tools/barcode_oligos/oligo_b.25mer.fw.fa'
SA = '/Users/herpov/Documents/mnt/tuba_home/tcr-pmhc-sc-project/tools/barcode_oligos/samples.fa'

In [128]:
OP = '/Users/herpov/Documents/mnt/tuba_home/tcr-pmhc-sc-project/tools/barcode_oligos/all_oligos.csv'

In [142]:
OFAFW = '/Users/herpov/Documents/mnt/tuba_home/tcr-pmhc-sc-project/tools/barcode_oligos/oligo.15mer.fw.fa'
OFARV = '/Users/herpov/Documents/mnt/tuba_home/tcr-pmhc-sc-project/tools/barcode_oligos/oligo.15mer.rv.fa'

In [63]:
from Bio.SeqIO.FastaIO import SimpleFastaParser
with open(SA) as fasta_file:  # Will close handle cleanly
    identifiers = []
    sequences = []
    for title, sequence in SimpleFastaParser(fasta_file):
        identifiers.append(title.split(None, 1)[0])  # First word is ID
        sequences.append(sequence)

In [64]:
identifiers

['bc25mer_21627',
 'bc25mer_22724',
 'bc25mer_23398',
 'bc25mer_29366',
 'bc25mer_51469']

In [59]:
df_oa = pd.DataFrame([identifiers, sequences]).T
df_oa.columns = ['oligo','seq_25mer']

In [62]:
df_ob = pd.DataFrame([identifiers, sequences]).T
df_ob.columns = ['oligo','seq_25mer']

In [65]:
df_sa = pd.DataFrame([identifiers, sequences]).T
df_sa.columns = ['oligo','seq_25mer']

In [43]:
df0 = pd.DataFrame([identifiers, sequences]).T

In [45]:
df0.columns = ['25mer_id','25mer_seq']

In [46]:
df0

              25mer_id                  25mer_seq
0            bc25mer_1  TATGAGGACGAATCTCCCGCTTATA
1            bc25mer_2  GGTCTTGACAAACGTGTGCTTGTAC
2            bc25mer_3  GTTTATCGGGCGTGGTGCTCGCATA
3            bc25mer_4  CCGATGTTGACGGACTAATCCTGAC
4            bc25mer_5  TAGTAGTTCAGACGCCGTTAAGCGC
...                ...                        ...
239995  bc25mer_239996  TGGGACATGTACATTTGCAGCGGTC
239996  bc25mer_239997  CTTACAAGTTCGCGTGGGCTCAGTG
239997  bc25mer_239998  GCTCGTAGTACCGTAAGCCAGATAC
239998  bc25mer_239999  CTGAGCAGATCAGTAGTCTTTACAT
239999  bc25mer_240000  GGCGCTATATTCCCGGAAATAATGG

[240000 rows x 2 columns]

In [17]:
df1 = pd.read_excel(F1)

In [18]:
df1

          15mer_id        25mer_id        15mer_seq usage
0      15bp_frac_1       bc25mer_1  TATGAGGACGAATCT   NaN
1      15bp_frac_2       bc25mer_4  CCGATGTTGACGGAC   NaN
2      15bp_frac_3       bc25mer_5  TAGTAGTTCAGACGC   NaN
3      15bp_frac_4       bc25mer_6  CCGTACCTAGATACA   NaN
4      15bp_frac_5      bc25mer_10  GGTATGGCACGCCTA   NaN
..             ...             ...              ...   ...
498  15bp_frac_499  bc25mer_213468  AAGGAGCCTGAGCTT   NaN
499  15bp_frac_500  bc25mer_217081  GATCGGCGACTAAGA   NaN
500  15bp_frac_501  bc25mer_228386  TACGGATGGTCGCTC   NaN
501  15bp_frac_502  bc25mer_235521  GGATTCCGGCCATGT   NaN
502  15bp_frac_503  bc25mer_237401  GGCTCTTGGAATGCA   NaN

[503 rows x 4 columns]

In [29]:
df2 = pd.read_excel(F2, sheet_name='Sequences', skiprows=9)

In [30]:
df2

,Name,5' modification,Primersite,N10,Barcode seq,N9,Capture seq,Full Seq (for ordering),15mer_id,oligo
0,sc-1OS_1,Biotin-C6-,CGGAGATGTGTATAAGAGACAG,NNNNNNNNNN,TATGAGGACGAATCT,NNNNNNNNN,CCCATATAAGAAA,Biotin-C6-CGGAGATGTGTATAAGAGACAGNNNNNNNNNNTATG...,sc-1OS_1,TATGAGGACGAATCT
1,sc-1OS_2,Biotin-C6-,CGGAGATGTGTATAAGAGACAG,NNNNNNNNNN,CCGATGTTGACGGAC,NNNNNNNNN,CCCATATAAGAAA,Biotin-C6-CGGAGATGTGTATAAGAGACAGNNNNNNNNNNCCGA...,sc-1OS_2,CCGATGTTGACGGAC
2,sc-1OS_3,Biotin-C6-,CGGAGATGTGTATAAGAGACAG,NNNNNNNNNN,TAGTAGTTCAGACGC,NNNNNNNNN,CCCATATAAGAAA,Biotin-C6-CGGAGATGTGTATAAGAGACAGNNNNNNNNNNTAGT...,sc-1OS_3,TAGTAGTTCAGACGC
3,sc-1OS_4,Biotin-C6-,CGGAGATGTGTATAAGAGACAG,NNNNNNNNNN,CCGTACCTAGATACA,NNNNNNNNN,CCCATATAAGAAA,Biotin-C6-CGGAGATGTGTATAAGAGACAGNNNNNNNNNNCCGT...,sc-1OS_4,CCGTACCTAGATACA
4,sc-1OS_5,Biotin-C6-,CGGAGATGTGTATAAGAGACAG,NNNNNNNNNN,GGTATGGCACGCCTA,NNNNNNNNN,CCCATATAAGAAA,Biotin-C6-CGGAGATGTGTATAAGAGACAGNNNNNNNNNNGGTA...,sc-1OS_5,GGTATGGCACGCCTA
...,...,...,...,...,...,...,...,...,...,...
187,sc-1OS_188,Biotin-C6-,CGGAGATGTGTATAAGAGACAG,NNNNNNNNNN,GAACTCCGTGGCTAA,NNNNNNNNN,CCCATATAAGAAA,Biotin-C6-CGGAGATGTGTATAAGAGACAGNNNNNNNNNNGAAC...,sc-1OS_188,GAACTCCGTGGCTAA
188,sc-1OS_189,Biotin-C6-,CGGAGATGTGTATAAGAGACAG,NNNNNNNNNN,CTCATGATGCTGCAT,NNNNNNNNN,CCCATATAAGAAA,Biotin-C6-CGGAGATGTGTATAAGAGACAGNNNNNNNNNNCTCA...,sc-1OS_189,CTCATGATGCTGCAT
189,sc-1OS_190,Biotin-C6-,CGGAGATGTGTATAAGAGACAG,NNNNNNNNNN,CGAATTACTGTGGTC,NNNNNNNNN,CCCATATAAGAAA,Biotin-C6-CGGAGATGTGTATAAGAGACAGNNNNNNNNNNCGAA...,sc-1OS_190,CGAATTACTGTGGTC
190,sc-1OS_191,Biotin-C6-,CGGAGATGTGTATAAGAGACAG,NNNNNNNNNN,TCCACATACAATGAC,NNNNNNNNN,CCCATATAAGAAA,Biotin-C6-CGGAGATGTGTATAAGAGACAGNNNNNNNNNNTCCA...,sc-1OS_191,TCCACATACAATGAC
191,sc-1OS_192,Biotin-C6-,CGGAGATGTGTATAAGAGACAG,NNNNNNNNNN,ATAGCACTATCCATC,NNNNNNNNN,CCCATATAAGAAA,Biotin-C6-CGGAGATGTGTATAAGAGACAGNNNNNNNNNNATAG...,sc-1OS_192,ATAGCACTATCCATC

In [47]:
df3 = pd.merge(df1, df2[['15mer_id','oligo']], left_on='15mer_seq',right_on='oligo', how='outer')

In [48]:
df3

,15mer_id_x,25mer_id,15mer_seq,usage,15mer_id_y,oligo
0,15bp_frac_1,bc25mer_1,TATGAGGACGAATCT,NaN,sc-1OS_1,TATGAGGACGAATCT
1,15bp_frac_2,bc25mer_4,CCGATGTTGACGGAC,NaN,sc-1OS_2,CCGATGTTGACGGAC
2,15bp_frac_3,bc25mer_5,TAGTAGTTCAGACGC,NaN,sc-1OS_3,TAGTAGTTCAGACGC
3,15bp_frac_4,bc25mer_6,CCGTACCTAGATACA,NaN,sc-1OS_4,CCGTACCTAGATACA
4,15bp_frac_5,bc25mer_10,GGTATGGCACGCCTA,NaN,sc-1OS_5,GGTATGGCACGCCTA
...,...,...,...,...,...,...
498,15bp_frac_499,bc25mer_213468,AAGGAGCCTGAGCTT,NaN,NaN,NaN
499,15bp_frac_500,bc25mer_217081,GATCGGCGACTAAGA,NaN,NaN,NaN
500,15bp_frac_501,bc25mer_228386,TACGGATGGTCGCTC,NaN,NaN,NaN
501,15bp_frac_502,bc25mer_235521,GGATTCCGGCCATGT,NaN,NaN,NaN
502,15bp_frac_503,bc25mer_237401,GGCTCTTGGAATGCA,NaN,NaN,NaN

In [111]:
df4 = pd.merge(df0, df3, left_on=['25mer_id'], right_on=['25mer_id'], how='outer')

In [112]:
df4

,25mer_id,25mer_seq,15mer_id_x,15mer_seq,usage,15mer_id_y,oligo
0,bc25mer_1,TATGAGGACGAATCTCCCGCTTATA,15bp_frac_1,TATGAGGACGAATCT,NaN,sc-1OS_1,TATGAGGACGAATCT
1,bc25mer_2,GGTCTTGACAAACGTGTGCTTGTAC,NaN,NaN,NaN,NaN,NaN
2,bc25mer_3,GTTTATCGGGCGTGGTGCTCGCATA,NaN,NaN,NaN,NaN,NaN
3,bc25mer_4,CCGATGTTGACGGACTAATCCTGAC,15bp_frac_2,CCGATGTTGACGGAC,NaN,sc-1OS_2,CCGATGTTGACGGAC
4,bc25mer_5,TAGTAGTTCAGACGCCGTTAAGCGC,15bp_frac_3,TAGTAGTTCAGACGC,NaN,sc-1OS_3,TAGTAGTTCAGACGC
...,...,...,...,...,...,...,...
239995,bc25mer_239996,TGGGACATGTACATTTGCAGCGGTC,NaN,NaN,NaN,NaN,NaN
239996,bc25mer_239997,CTTACAAGTTCGCGTGGGCTCAGTG,NaN,NaN,NaN,NaN,NaN
239997,bc25mer_239998,GCTCGTAGTACCGTAAGCCAGATAC,NaN,NaN,NaN,NaN,NaN
239998,bc25mer_239999,CTGAGCAGATCAGTAGTCTTTACAT,NaN,NaN,NaN,NaN,NaN
239999,bc25mer_240000,GGCGCTATATTCCCGGAAATAATGG,NaN,NaN,NaN,NaN,NaN

In [113]:
df4.rename(columns={'25mer_id':'id_25mer','25mer_seq':'seq_25mer_fw','15mer_id_x':'id_15mer_2','15mer_seq':'seq_15mer_fw','15mer_id_y':'id_15mer_1'}, inplace=True)

In [114]:
df4.oligo = np.nan

In [115]:
oligos = pd.concat([df_oa, df_ob])

In [116]:
oligos

    oligo                  seq_25mer
0   A4000  CTGCGGGTATAGGACCTTGATAACC
1   A1064  CGTAGTAGCTATCTCCTTATGACAA
2   A1065  GACCGCAAAGTGCAAGTAACTACCG
3   A1066  CGCTTGTTATTATCTGCCTGCAAGC
4   A1067  GCGCACAGATTCCGCTGCATGATAC
..    ...                        ...
50   B338  TGGCAAGCATCCGACGCAATAGGAA
51   B339  TGTCTATAGCAGGGCTGGCCATCTC
52   B340  CTTACTTTCCAACGGGGCCCATCAG
53   B341  ATTCTGCGTATTTCGATCTACACTC
54   B342  TTAGTGTACATGCCTGGCTCGGACG

[76 rows x 2 columns]

In [117]:
df4.oligo = df4.seq_25mer_fw.map(oligos.set_index('seq_25mer').oligo)

In [118]:
df4[~df4.oligo.isna()]

,id_25mer,seq_25mer_fw,id_15mer_2,seq_15mer_fw,usage,id_15mer_1,oligo
2098,bc25mer_2099,CTTGGCAATCCATGCTCCCATTTGG,NaN,NaN,NaN,NaN,B288
2099,bc25mer_2100,GAACCATGTGGCTTGCTTCAACTTC,NaN,NaN,NaN,NaN,B289
2100,bc25mer_2101,GCCTGTAGTCCCACGCGATCTAACA,NaN,NaN,NaN,NaN,B290
2295,bc25mer_2296,GTTTACGTGAGTTGGAGGACTTTAT,NaN,NaN,NaN,NaN,B291
2296,bc25mer_2297,GTATCAAGAGACGCTCTACCGGGAT,NaN,NaN,NaN,NaN,B292
...,...,...,...,...,...,...,...
3079,bc25mer_3080,ACCGGAGATTGCGTTACCAAGGTTA,NaN,NaN,NaN,NaN,A1080
3080,bc25mer_3081,ATACTATACGGATCCTTACTGCCAG,NaN,NaN,NaN,NaN,A1081
3081,bc25mer_3082,ATCTACATTGACTCTATGCTTTCGT,NaN,NaN,NaN,NaN,A1082
3082,bc25mer_3083,CTAGTTGTGACAGCCTCTCGGTACT,NaN,NaN,NaN,NaN,A1083
3999,bc25mer_4000,CTGCGGGTATAGGACCTTGATAACC,NaN,NaN,NaN,NaN,A4000

In [119]:
df_sa

           oligo seq_25mer
0  bc25mer_21627  TTGGAGAG
1  bc25mer_22724  GCCGTTAA
2  bc25mer_23398  TTGCTTGA
3  bc25mer_29366  GCACAGGA
4  bc25mer_51469  TTCAGCCT

In [120]:
df4.loc[df4.id_25mer.isin(df_sa.oligo), 'oligo'] = 'sample'

In [121]:
df4.loc[df4.id_25mer.isin(df_sa.oligo)]

,id_25mer,seq_25mer_fw,id_15mer_2,seq_15mer_fw,usage,id_15mer_1,oligo
21626,bc25mer_21627,CTGTGTACTAGTGCTACTCTCCAAT,NaN,NaN,NaN,NaN,sample
22723,bc25mer_22724,TTAACGGCTTGAGCTGACGACCAAT,NaN,NaN,NaN,NaN,sample
23397,bc25mer_23398,CTCATGCAGGTACGGCTCAAGCAAG,NaN,NaN,NaN,NaN,sample
29365,bc25mer_29366,TGTAGCAGTCCTGTGCCCGATTCAT,NaN,NaN,NaN,NaN,sample
51468,bc25mer_51469,AGGCTGAATATTCTCCGGATTCCTC,NaN,NaN,NaN,NaN,sample

In [122]:
df4

,id_25mer,seq_25mer_fw,id_15mer_2,seq_15mer_fw,usage,id_15mer_1,oligo
0,bc25mer_1,TATGAGGACGAATCTCCCGCTTATA,15bp_frac_1,TATGAGGACGAATCT,NaN,sc-1OS_1,NaN
1,bc25mer_2,GGTCTTGACAAACGTGTGCTTGTAC,NaN,NaN,NaN,NaN,NaN
2,bc25mer_3,GTTTATCGGGCGTGGTGCTCGCATA,NaN,NaN,NaN,NaN,NaN
3,bc25mer_4,CCGATGTTGACGGACTAATCCTGAC,15bp_frac_2,CCGATGTTGACGGAC,NaN,sc-1OS_2,NaN
4,bc25mer_5,TAGTAGTTCAGACGCCGTTAAGCGC,15bp_frac_3,TAGTAGTTCAGACGC,NaN,sc-1OS_3,NaN
...,...,...,...,...,...,...,...
239995,bc25mer_239996,TGGGACATGTACATTTGCAGCGGTC,NaN,NaN,NaN,NaN,NaN
239996,bc25mer_239997,CTTACAAGTTCGCGTGGGCTCAGTG,NaN,NaN,NaN,NaN,NaN
239997,bc25mer_239998,GCTCGTAGTACCGTAAGCCAGATAC,NaN,NaN,NaN,NaN,NaN
239998,bc25mer_239999,CTGAGCAGATCAGTAGTCTTTACAT,NaN,NaN,NaN,NaN,NaN
239999,bc25mer_240000,GGCGCTATATTCCCGGAAATAATGG,NaN,NaN,NaN,NaN,NaN

In [123]:
transtable = str.maketrans("ACTG","TGAC")

In [124]:
df4['seq_25mer_rv'] = df4.seq_25mer_fw.apply(lambda x: x.translate(transtable)[::-1])

In [125]:
df4['seq_15mer_rv'] = df4.seq_15mer_fw.apply(lambda x: x.translate(transtable)[::-1] if x == x else np.nan)

In [130]:
df4[['id_25mer','seq_25mer_fw','seq_25mer_rv',
     'id_15mer_1','id_15mer_2','seq_15mer_fw','seq_15mer_rv',
     'oligo']].to_csv(OP, index=False)

In [144]:
df4[~df4.seq_15mer_fw.isna()].head(15)

,id_25mer,seq_25mer_fw,id_15mer_2,seq_15mer_fw,usage,id_15mer_1,oligo,seq_25mer_rv,seq_15mer_rv
0,bc25mer_1,TATGAGGACGAATCTCCCGCTTATA,15bp_frac_1,TATGAGGACGAATCT,NaN,sc-1OS_1,NaN,TATAAGCGGGAGATTCGTCCTCATA,AGATTCGTCCTCATA
3,bc25mer_4,CCGATGTTGACGGACTAATCCTGAC,15bp_frac_2,CCGATGTTGACGGAC,NaN,sc-1OS_2,NaN,GTCAGGATTAGTCCGTCAACATCGG,GTCCGTCAACATCGG
4,bc25mer_5,TAGTAGTTCAGACGCCGTTAAGCGC,15bp_frac_3,TAGTAGTTCAGACGC,NaN,sc-1OS_3,NaN,GCGCTTAACGGCGTCTGAACTACTA,GCGTCTGAACTACTA
5,bc25mer_6,CCGTACCTAGATACACTCAATTTGT,15bp_frac_4,CCGTACCTAGATACA,NaN,sc-1OS_4,NaN,ACAAATTGAGTGTATCTAGGTACGG,TGTATCTAGGTACGG
9,bc25mer_10,GGTATGGCACGCCTAATCTGGACAC,15bp_frac_5,GGTATGGCACGCCTA,NaN,sc-1OS_5,NaN,GTGTCCAGATTAGGCGTGCCATACC,TAGGCGTGCCATACC
10,bc25mer_11,GGATGCATGATCTAGGGCCTCGTCT,15bp_frac_6,GGATGCATGATCTAG,NaN,sc-1OS_6,NaN,AGACGAGGCCCTAGATCATGCATCC,CTAGATCATGCATCC
12,bc25mer_13,GATTCAATATGTGTCGTCTATCCTC,15bp_frac_7,GATTCAATATGTGTC,NaN,sc-1OS_7,NaN,GAGGATAGACGACACATATTGAATC,GACACATATTGAATC
13,bc25mer_14,GGTAACTGCGCATAGTTGGCTCTAT,15bp_frac_8,GGTAACTGCGCATAG,NaN,sc-1OS_8,NaN,ATAGAGCCAACTATGCGCAGTTACC,CTATGCGCAGTTACC
19,bc25mer_20,GGTACAGTAAGTGAGAATCCTCTCT,15bp_frac_9,GGTACAGTAAGTGAG,NaN,sc-1OS_9,NaN,AGAGAGGATTCTCACTTACTGTACC,CTCACTTACTGTACC
22,bc25mer_23,GCCACCTTAACACGCGATGATATTG,15bp_frac_10,GCCACCTTAACACGC,NaN,sc-1OS_10,NaN,CAATATCATCGCGTGTTAAGGTGGC,GCGTGTTAAGGTGGC
23,bc25mer_24,GCTATTACGAGCGCTTGGATCCCGT,15bp_frac_11,GCTATTACGAGCGCT,NaN,sc-1OS_11,NaN,ACGGGATCCAAGCGCTCGTAATAGC,AGCGCTCGTAATAGC
24,bc25mer_25,TATGTTGTGCCTTACGCCTCGATTA,15bp_frac_12,TATGTTGTGCCTTAC,NaN,sc-1OS_12,NaN,TAATCGAGGCGTAAGGCACAACATA,GTAAGGCACAACATA
25,bc25mer_26,TTAACCGAACTGACGGCCATCAAGG,15bp_frac_13,TTAACCGAACTGACG,NaN,sc-1OS_13,NaN,CCTTGATGGCCGTCAGTTCGGTTAA,CGTCAGTTCGGTTAA
27,bc25mer_28,TTCTATTCTAAGCCGGCGGTCATAT,15bp_frac_14,TTCTATTCTAAGCCG,NaN,sc-1OS_14,NaN,ATATGACCGCCGGCTTAGAATAGAA,CGGCTTAGAATAGAA
29,bc25mer_30,TCCAAGTTAGCTTACTCCATGCCCC,15bp_frac_15,TCCAAGTTAGCTTAC,NaN,sc-1OS_15,NaN,GGGGCATGGAGTAAGCTAACTTGGA,GTAAGCTAACTTGGA

In [139]:
records = list()
for i, row in df4[~df4.seq_15mer_fw.isna()].iterrows():
    records.append(SeqRecord(Seq(row.seq_15mer_rv), id=row.id_15mer_2))

In [140]:
records

[SeqRecord(seq=Seq('AGATTCGTCCTCATA'), id='15bp_frac_1', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTCCGTCAACATCGG'), id='15bp_frac_2', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCGTCTGAACTACTA'), id='15bp_frac_3', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTATCTAGGTACGG'), id='15bp_frac_4', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TAGGCGTGCCATACC'), id='15bp_frac_5', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTAGATCATGCATCC'), id='15bp_frac_6', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GACACATATTGAATC'), id='15bp_frac_7', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTATGCGCAGTTACC'), id='15bp_frac_8', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTCACTTACTGTACC'), id='15bp_frac_9', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCGTGTTAAGGTGGC'), id='15bp_frac_10', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGCGCTCGTAATAGC'), id='15bp_frac_11', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTAAGGCACAACATA'), id='15bp_frac_12', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTCAGTTCGGTTAA'), id='15bp_frac_13', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGGCTTAGAATAGAA'), id='15bp_frac_14', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTAAGCTAACTTGGA'), id='15bp_frac_15', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCCTAATTAACAG'), id='15bp_frac_16', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCATAGGACTACCT'), id='15bp_frac_17', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTATAGTCCAAGCC'), id='15bp_frac_18', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GGTATAATACGACGT'), id='15bp_frac_19', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CAATGTCTGCGGCAC'), id='15bp_frac_20', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATATGAACGGTGCA'), id='15bp_frac_21', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TTCGAGACAGCTCAT'), id='15bp_frac_22', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGACCGAGAAGAAGT'), id='15bp_frac_23', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGCGTATATGTATCC'), id='15bp_frac_24', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGTAATACAACCTGT'), id='15bp_frac_25', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATCGGCGCCACTTAG'), id='15bp_frac_26', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTGGATATTCGACTC'), id='15bp_frac_27', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTATAGCCAGAACTA'), id='15bp_frac_28', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TTATTCACCATTCAG'), id='15bp_frac_29', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATATCTTACTACG'), id='15bp_frac_30', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GAACTAGACCTACGC'), id='15bp_frac_31', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TAGAACCACGTAGAC'), id='15bp_frac_32', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGTATGACATGTACA'), id='15bp_frac_33', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TGGCGTACATGTCAA'), id='15bp_frac_34', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATCGTACTGAATTGC'), id='15bp_frac_35', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AACCTGCTCGTCTAA'), id='15bp_frac_36', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCGCAAGTTGATCAG'), id='15bp_frac_37', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGAATGCTGAACGC'), id='15bp_frac_38', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGAGCTCTCATAAGG'), id='15bp_frac_39', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AACGTTACTCAGTAA'), id='15bp_frac_40', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGGAATAAGTAT'), id='15bp_frac_41', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CAGACACGTTAGGAG'), id='15bp_frac_42', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTAGTTGGTACGCTT'), id='15bp_frac_43', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTGGCCGACACAA'), id='15bp_frac_44', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAGGCGACAATCAC'), id='15bp_frac_45', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CCGCCACCTATTATA'), id='15bp_frac_46', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGAGCAGGACTTGTT'), id='15bp_frac_47', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACACCTCATCCAGG'), id='15bp_frac_48', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GGAACATAATCGCTA'), id='15bp_frac_49', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTCTCCTATATCGCC'), id='15bp_frac_50', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GACGTTCCAGTTAGC'), id='15bp_frac_51', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATCCATCCTCGAATA'), id='15bp_frac_52', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GAATATAACGTGAGA'), id='15bp_frac_53', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GGCCGGTAATGGTAT'), id='15bp_frac_54', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAGCGAGTAGAGCG'), id='15bp_frac_55', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATCGCGAGCTTACTT'), id='15bp_frac_56', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TGCGAACCAGAATGC'), id='15bp_frac_57', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTACTTGTGTTATGC'), id='15bp_frac_58', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GGATGTGCCTCCTTC'), id='15bp_frac_59', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTACGGACATAGCC'), id='15bp_frac_60', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGTCGATTGTCGCTC'), id='15bp_frac_61', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTTAGACAACGATTC'), id='15bp_frac_62', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CAGGTACCATGGTTC'), id='15bp_frac_63', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGCATATCGAGAACT'), id='15bp_frac_64', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGATTATCCATAGA'), id='15bp_frac_65', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCTCGCAATGTTATA'), id='15bp_frac_66', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GGATCGTATGATCTA'), id='15bp_frac_67', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CCGGTTGGATGATGG'), id='15bp_frac_68', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACGAGGAATCACGGA'), id='15bp_frac_69', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CAGGATAACAGGTAT'), id='15bp_frac_70', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CAATTATTCCAGAGG'), id='15bp_frac_71', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTCGATATCAGTCC'), id='15bp_frac_72', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AATCGATAACGGCTA'), id='15bp_frac_73', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCGTTGTCATCGTC'), id='15bp_frac_74', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GACGCCGAGGATATC'), id='15bp_frac_75', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TATAGCTAGGAATAC'), id='15bp_frac_76', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTGTTGTCGGTGGCT'), id='15bp_frac_77', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GGCTAGAAGTCCTTA'), id='15bp_frac_78', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTTCGGATCAATTCG'), id='15bp_frac_79', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAACTCACCTTAT'), id='15bp_frac_80', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AACATAGTCACGCCA'), id='15bp_frac_81', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TAGGAGCACGTCTCA'), id='15bp_frac_82', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CCTGGTTACACAATC'), id='15bp_frac_83', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTAAGCACAATGCTA'), id='15bp_frac_84', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTAAGTGCAAGCAC'), id='15bp_frac_85', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CCGACCTTACGCCTA'), id='15bp_frac_86', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTGTTCGCACTAGT'), id='15bp_frac_87', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTAACGAAGTGCTCT'), id='15bp_frac_88', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CCACGATGTCACAAC'), id='15bp_frac_89', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TAGCACGATCGCTTC'), id='15bp_frac_90', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGATATGCCAGGCTT'), id='15bp_frac_91', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CCACAACTGCCGTAT'), id='15bp_frac_92', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCAACGAATGCCATG'), id='15bp_frac_93', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTAGTCTCAGTCAAC'), id='15bp_frac_94', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGGTAACAATTCACA'), id='15bp_frac_95', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TAGGATCACACTCGC'), id='15bp_frac_96', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AACGGCAATCATGTC'), id='15bp_frac_97', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTAGTATCTCCTCGC'), id='15bp_frac_98', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATCAGACCATAGTG'), id='15bp_frac_99', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCTCATGACCAATCA'), id='15bp_frac_100', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TTGAGAGCACTTATG'), id='15bp_frac_101', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGGTGAGATTCACGC'), id='15bp_frac_102', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCTAGTAGGAGATTG'), id='15bp_frac_103', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGACGTGACTCTA'), id='15bp_frac_104', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCGACATCAAGTAAG'), id='15bp_frac_105', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCTGTCTACCGATGA'), id='15bp_frac_106', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCCGAATATGCAGA'), id='15bp_frac_107', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGACACCAGAGTTC'), id='15bp_frac_108', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CCGTACCAGTTCTAT'), id='15bp_frac_109', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTCTGATTGTTGCT'), id='15bp_frac_110', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AATTATCGACTTACG'), id='15bp_frac_111', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CCACTTCTCCAGGCA'), id='15bp_frac_112', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TAGCATACTCCGGAT'), id='15bp_frac_113', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TGCGGATATACTGGA'), id='15bp_frac_114', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TTGGCAACACACGAG'), id='15bp_frac_115', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATAACACTCTGTCC'), id='15bp_frac_116', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCACGGCATTGGTA'), id='15bp_frac_117', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCCACTACGTCATCT'), id='15bp_frac_118', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTCGAGATTAGGTG'), id='15bp_frac_119', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CCATGAAGTAGCTAA'), id='15bp_frac_120', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATACATCGAACGTAA'), id='15bp_frac_121', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AAGCTATCATTAGCG'), id='15bp_frac_122', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCCGCTACTAATCAG'), id='15bp_frac_123', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCTGGAGCTGGATAC'), id='15bp_frac_124', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGAGCATAGATCCAA'), id='15bp_frac_125', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCTATCAGCGACTCG'), id='15bp_frac_126', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TTCCGCAACGGTCCT'), id='15bp_frac_127', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTCAATCCACTATGC'), id='15bp_frac_128', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCAAGGCTCTAAT'), id='15bp_frac_129', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGGCGACTAATA'), id='15bp_frac_130', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCCAGAGAGTATACC'), id='15bp_frac_131', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGCTATTCCTACCTC'), id='15bp_frac_132', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCTCCTGCATATGTC'), id='15bp_frac_133', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGTAGTGCGTGAAGC'), id='15bp_frac_134', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CAATCTGCCGAGTAC'), id='15bp_frac_135', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGACTGATATGACT'), id='15bp_frac_136', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGCTAGCAACGT'), id='15bp_frac_137', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GGCATAACTACACCG'), id='15bp_frac_138', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CAGTCTCGTCAAGTC'), id='15bp_frac_139', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCTAAGCGATACAA'), id='15bp_frac_140', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AGGCGGAGCAACAAT'), id='15bp_frac_141', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCCATAAGAATCGAC'), id='15bp_frac_142', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCTACAACAGAACCT'), id='15bp_frac_143', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTCTGCCAGCTAGTG'), id='15bp_frac_144', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CAGATGCCTCAACCG'), id='15bp_frac_145', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CCACCGAATCTCTGT'), id='15bp_frac_146', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TGCAACCAATAGCGT'), id='15bp_frac_147', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CGATAGTACCGAACT'), id='15bp_frac_148', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GCGTATCCTTGATGC'), id='15bp_frac_149', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TTCGCAGCGTGTCAT'), id='15bp_frac_150', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TGCACCATCGATTCC'), id='15bp_frac_151', name='<unknown name>', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GATCCTCAGGTCTTC'), id='15bp_frac_152', name='<unknown name>', description='<unknown description>', dbxrefs=[]),

In [143]:
SeqIO.write(records, OFARV, "fasta")

503