In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
plt.style.use('ggplot')

# Args

In [22]:
EXP = "exp6"
PLATFORM = "IONTORRENT"
MAPPING = 'KMA' # BLAST
BARCODE_SYSTEM = 'AKB' #'AKB' #

# Input

In [23]:
IN_FIL = ("/Volumes/tuba/herpov/tcr-pmhc-sc-project/data/" + EXP + "_MHC_" + PLATFORM +
          "/mapping/KMA-1t1/output/mapping.clean." + BARCODE_SYSTEM + ".augmented.gz")

# Main

In [24]:
df = pd.read_csv(IN_FIL, sep="\t")

In [25]:
df

,gem,credible_alignment_mhc,credible_alignment_cd8,template_id_mhc,read_counts_mhc,read_count_diff_mhc,single_barcode_mhc,read_counts_lst_mhc,template_lst_mhc,template_id_cd8,...,peptide,HLA,epitope,epitope_lst,Unnamed: 21,ADIR,HA-1,HA-2,v14,v15
0,AAACCTGCAGGAACGT-1,True,NaN,A1068B288_sample,1.0,1.0,True,[1],['A1068B288_sample'],NaN,...,SVAPALALFPA,A0201,ADIR,['ADIR'],NaN,1.0,NaN,NaN,NaN,NaN
1,AAACCTGTCTGCGGCA-1,True,NaN,A1068B288_sample,1.0,1.0,True,[1],['A1068B288_sample'],NaN,...,SVAPALALFPA,A0201,ADIR,['ADIR'],NaN,1.0,NaN,NaN,NaN,NaN
2,AAACGGGAGGGAACGG-1,True,NaN,A1068B288_sample,454.0,1.0,True,[454],['A1068B288_sample'],NaN,...,SVAPALALFPA,A0201,ADIR,['ADIR'],NaN,454.0,NaN,NaN,NaN,NaN
3,AAACGGGTCTAAGCCA-1,True,NaN,A1064B288_sample,1.0,1.0,True,[1],['A1064B288_sample'],NaN,...,VTEHDTLLY,A0101,v15,['v15'],NaN,NaN,NaN,NaN,NaN,1.0
4,AAAGATGAGGCTACGA-1,True,NaN,A1069B288_sample,1.0,1.0,True,[1],['A1069B288_sample'],NaN,...,NaN,NaN,NaN,[nan],1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,TTTACTGGTAAACGCG-1,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,A4000B289_sample,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1402,TTTATGCAGTGCAGAC-1,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,A4000B288_sample,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1403,TTTCCTCCAAACCCAT-1,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,A4000B295_sample,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1404,TTTGGTTGTCCAGTGC-1,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,A4000B297_sample,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1405,TTTGTCACATGCGCAC-1,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,A4000B294_sample,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df.groupby('template_id_cd8').size()

template_id_cd8
A4000B288_sample    47
A4000B289_sample    28
A4000B290_sample    98
A4000B291_sample    27
A4000B292_sample    44
A4000B293_sample    23
A4000B294_sample    36
A4000B295_sample    34
A4000B296_sample    27
A4000B297_sample    29
A4000B298_sample    30
A4000B300_sample    17
A4000B301_sample     4
A4000B302_sample    30
dtype: int64